# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fluentd", "~> 0.12.0"
gem "fluent-plugin-bigquery", "~> 0.4.0"
gem "fluent-plugin-elasticsearch", "~> 1.13.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 1.6.0"
