FROM fluent/fluentd:v1.7-debian-1

# Use root account to use apt
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN buildDeps="sudo make gcc g++ libc-dev" \
    && apt-get update \
    && apt-get install -y --no-install-recommends $buildDeps \
    && sudo gem install \
         fluent-plugin-bigquery:2.2.0 \
         fluent-plugin-elasticsearch:3.5.5 \
         fluent-plugin-rewrite-tag-filter:2.2.0 \
         fluent-plugin-prometheus:1.6.0 \
    && sudo gem sources --clear-all \
    && SUDO_FORCE_REMOVE=yes \
       apt-get purge -y --auto-remove \
         -o APT::AutoRemove::RecommendsImportant=false \
         $buildDeps \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER fluent
